### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by thienkieu** [khanguyen01it/PNV-landing-page-ReactJS-Laravel#1]
component table
 - id: nvarchar(40) 
 - name: nvarchar(500)
 - code_name: nvarchar(200)
 - params: Json

landingpage table
 - id:
 - url:
 - description:
 - meta data
 - title

page_component table
- id 
- page_id
- component_id
- order
- params: Json
- page_type: blog or landing page

blog table
- id
- url
- ...
- 
user table
....

**Comment by thienkieu** [comment]
table blog va landing page có  thể gọp lại 1 table, e  xem  có  nên  gôp  ko, gop  thi có lợi gì

**Comment by khanguyen01it** [comment]
E thấy các trường dữ liệu nó khá giống nhau nhưng mục đích nó khác nhau, e nghĩ là không gộp a ạ :D

**Comment by thienkieu** [comment]
ok  e, cái  đó  mình  tính  sau, giờ  làm  cái  landing  page trước đã

**Comment by khanguyen01it** [comment]
Dạ a.
